name: Build index.js
on:
  push:
  pull_request:

jobs:
  build-on-push:
    if: >-
      github.actor != 'UbiquiBot[dev]' &&
      github.event.pull_request.payload.sender.type != 'Bot' &&
      github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.0"

      - name: Install
        run: yarn install

      - name: Prettier
        run: yarn format:check

      - name: Local Build
        run: yarn build

      - name: Authenticate SSH
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.UBIQUITY_BOUNTY_BOT_DEV_PRIVATE_KEY_OPENSSH }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Commit and Push Changes
        run: |
          git config --local user.email "UbiquiBot[dev]@github.com"
          git config --local user.name "UbiquiBot[dev]"
          yarn build:ci
          git add -A
          git diff-index --quiet HEAD || git commit -am "build: update executable" --no-verify
          git push git@github.com:${{github.repository}}.git ${{github.ref}}
        env:
          GITHUB_TOKEN: ${{ secrets.UBIQUITY_BOUNTY_BOT_DEV_PRIVATE_KEY_OPENSSH }}
