name: Deploy Log Web App to Cloudflare Worker

# on:
#   workflow_run:
#     workflows: ["Conventional Commits"]
#     types:
#       - completed

on:
  push:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Worker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.3.0"

      - name: Yarn Install
        run: yarn install

      - name: Wrangler Install
        run: npm install -g wrangler

      - name: Publish to Cloudflare Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          cd ./log-app && yarn deploy
          echo "$SUPABASE_URL" | wrangler secret put SUPABASE_URL
          echo "$SUPABASE_KEY" | wrangler secret put SUPABASE_KEY
