name: Enforce Kebab Case Filenames

on:
  push:
  pull_request:

jobs:
  check_filenames:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check Filenames
        run: |
          for file in $(git ls-files); do
            basefile=$(basename "$file")
            if [[ $file == .*/* ]] || [[ $file == */* ]] || [[ $basefile =~ ^[^/]*$ ]] || [[ $basefile =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
              continue
            else
              echo "File $file is not in kebab-case, UPPER_CASE, or .lowercase"
              exit 1
            fi
          done
