name: Knip

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run Knip
        run: npx knip --reporter json > knip-output.json

      - name: Annotate Pull Request
        run: npx tsx create-annotations.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}