name: Knip

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"

      - name: Install dependencies
        run: yarn add knip tsx

      - name: Run Knip
        run: npx knip --reporter json > knip-output.json

      - name: Annotate Pull Request
        run: npx tsx create-annotations.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
