name: Say Hello World
on:
  issues:
    types:
      # - opened
      - labeled
      - unlabeled

jobs:
  # sayHelloWorld:
    # runs-on: ubuntu-latest
    # name: A job to say hello world
    # steps:
      # - uses: probot/example-github-action@v1
        # with:
          # token: ${{ secrets.GITHUB_TOKEN }}
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # or
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        run: ./dist # Uses an action in the root directory
        id: hello
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      # - name: Get the output time
        # run: echo "The time was ${{ steps.hello.outputs.time }}"