name: Build and Test
on:
  push:

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install
        run: yarn install

      - name: Prettier
        run: yarn prettier:check

      - name: Build Serverless Functions
        run: yarn build:serverless
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Build: Update dist/index.js"
          git push origin ${{github.ref}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}