name: Build and Test
on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check Commit Author
      id: check_author
      run: |
        author=$(git log -1 --pretty=%an)
        if [ "$author" == "UbiquiBot[dev]" ]; then
          echo "Error: Commit author is UbiquiBot[dev]"
          exit 1
        else
          echo "Commit author is not UbiquiBot[dev], proceeding with action"
        fi

  install-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install
        run: yarn install

      - name: Prettier
        run: yarn prettier:check

      - name: Authenticate SSH
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.UBIQUITY_BOUNTY_BOT_DEV_PRIVATE_KEY_OPENSSH }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Commit and Push Changes
        run: |
          git config --local user.email "UbiquiBot[dev]@github.com"
          git config --local user.name "UbiquiBot[dev]"
          yarn build:serverless
          git add -A
          git diff-index --quiet HEAD || git commit -am "Build: Update dist/index.js" --no-verify
          git push git@github.com:${{github.repository}}.git ${{github.ref}}
        env:
          GITHUB_TOKEN: ${{ secrets.UBIQUITY_BOUNTY_BOT_DEV_PRIVATE_KEY_OPENSSH }}