name: Build and Test
on:
  push:

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install
        run: yarn install

      - name: Prettier
        run: yarn prettier:check

      - name: Authenticate SSH
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.UBIQUITY_BOUNTY_BOT_DEV_PRIVATE_KEY }}

      - name: Commit and Push Changes
        run: |
          git config --local user.email "UbiquiBot[dev]@github.com"
          git config --local user.name "UbiquiBot[dev]"
          yarn build:serverless
          git commit -am "Build: Update dist/index.js" --no-verify
          git push origin ${{github.ref}}
        env:
          GITHUB_TOKEN: ${{ secrets.UBIQUITY_BOUNTY_BOT_DEV_PRIVATE_KEY }}