name: Add pull requests to project

on:
  pull_request:
    types:
      - review_requested

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: add pr to project
        if: contains(github.event.pull_request.requested_reviewers.*.login, 'Draeieg')
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/ubiquity/projects/23
          github-token: ${{ secrets.UBIQUITY_BOUNTY_BOT_PRIVATE_KEY_DEV }}
      - name: Create QA Issue
        if: contains(github.event.pull_request.requested_reviewers.*.login, 'Draeieg')
        uses: dacbd/create-issue-action@v1
        with:
          token: ${{ secrets.UBIQUITY_BOUNTY_BOT_PRIVATE_KEY_DEV }}
          org: ubiquibot
          repo: staging
          title: QA for ${{ github.event.pull_request.title }}
          body: |
            Testing pr <a href="${{ github.event.pull_request.html_url }}">${{ github.event.pull_request.number }}</a>
