name: Releases
on: 
  create:
    tag:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0