name: Releases
on:
  create:
    tag:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0

      - name: Clear Unused Labels
        run: |
            npx tsx -e "import { clearUnusedLabels } from '.github/workflows/clear-unused-labels/clear-unused-labels.ts'; clearUnusedLabels(${{github.repository}}, ${{github.token}});"
